[package]
name = "revision-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" }
serde_json = { version = "1.0" }
md5 = "0.7.0"
bytes = "1.4"
