# https://rust-lang.github.io/rustfmt/?version=master&search=
max_width = 120
tab_spaces = 4
fn_single_line = true
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
report_todo = "Always"
report_fixme = "Always"
imports_layout = "HorizontalVertical"
enum_discrim_align_threshold = 20
edition = "2018"
