[package]
name = "user-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" }
validator = "0.16.0"
unicode-segmentation = "1.8"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
tracing = { version = "0.1", features = ["log"] }
error-code = { path = "../error-code" }

[dev-dependencies]
nanoid = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "0.9.1"
fake = "2.4.3"
claim = "0.4.0"
futures = "0.3.15"
serial_test = "0.5.1"
rand_core = "0.6.3"
rand = "0.8.5"