[package]
name = "flowy-folder2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { version = "0.1.0" }
collab-folder = { version = "0.1.0" }
collab-entity = { version = "0.1.0" }
collab-integrate = { workspace = true }
flowy-folder-deps = { workspace = true }

flowy-derive = { path = "../../../shared-lib/flowy-derive" }
flowy-notification  = { workspace = true }
parking_lot.workspace = true
unicode-segmentation = "1.10"
tracing.workspace = true
flowy-error = { path = "../flowy-error", features = ["impl_from_dispatch_error"]}
lib-dispatch = { workspace = true }
bytes.workspace = true
lib-infra = { path = "../../../shared-lib/lib-infra" }
tokio = { workspace = true, features = ["full"] }
nanoid = "0.4.0"
lazy_static = "1.4.0"
chrono = { workspace = true,  default-features = false, features = ["clock"] }
strum_macros = "0.21"
protobuf.workspace = true
uuid.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
serde_json.workspace = true

[build-dependencies]
flowy-codegen = { path = "../../../shared-lib/flowy-codegen"}

[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
ts = ["flowy-codegen/ts", "flowy-notification/ts"]
test_helper = []