[package]
name = "flowy-folder2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { version = "0.1.0" }
collab-folder = { version = "0.1.0" }
appflowy-integrate = {version = "0.1.0" }
flowy-folder-deps = { path = "../flowy-folder-deps" }

flowy-derive = { path = "../../../shared-lib/flowy-derive" }
flowy-notification = { path = "../flowy-notification" }
parking_lot = "0.12.1"
unicode-segmentation = "1.10"
tracing = { version = "0.1", features = ["log"] }
flowy-error = { path = "../flowy-error", features = ["impl_from_dispatch_error"]}
lib-dispatch = { path = "../lib-dispatch" }
bytes = { version = "1.4" }
lib-infra = { path = "../../../shared-lib/lib-infra" }
tokio = { version = "1.26", features = ["full"] }
nanoid = "0.4.0"
lazy_static = "1.4.0"
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
strum_macros = "0.21"
protobuf = {version = "2.28.0"}
uuid = { version = "1.3.3", features = ["v4"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }

[dev-dependencies]
flowy-folder2 = { path = "../flowy-folder2"}
flowy-test = { path = "../flowy-test", default-features = false }

[build-dependencies]
flowy-codegen = { path = "../../../shared-lib/flowy-codegen"}

[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
ts = ["flowy-codegen/ts", "flowy-notification/ts"]
test_helper = []