# https://rust-lang.github.io/rustfmt/?version=master&search=
max_width = 120
tab_spaces = 4
fn_single_line = true
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
report_todo = "Never"
report_fixme = "Always"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_modules = true
reorder_imports = true
enum_discrim_align_threshold = 20
edition = "2018"
