[package]
name = "flowy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1" }
futures-util = "0.3.26"
reqwest = "0.11.14"
hyper = "0.14"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-aux = "4.2.0"
nanoid = "0.4.0"
thiserror = "1.0"
tokio = { version = "1.26", features = ["sync"]}
parking_lot = "0.12"
lazy_static = "1.4.0"
bytes = "1.0.1"
tokio-retry = "0.3"
anyhow = "1.0"
uuid = { version = "1.3.3", features = ["v4"] }
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }

postgrest = "1.0"
tokio-postgres = { version = "0.7.8", optional = true, features = ["with-uuid-1","with-chrono-0_4"] }
refinery= { version = "0.8.10", optional = true, features = ["tokio-postgres"] }

lib-infra = { path = "../../../shared-lib/lib-infra" }
flowy-user = { path = "../flowy-user" }
flowy-folder2 = { path = "../flowy-folder2" }
flowy-error = { path = "../flowy-error" }

[dev-dependencies]
uuid = { version = "1.3.3", features = ["v4"] }
dotenv = "0.15.0"

[features]
default = ["postgres_storage"]
postgres_storage = ["tokio-postgres", "refinery"]
