[package]
name = "flowy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
futures.workspace = true
futures-util = "0.3.26"
reqwest = { version = "0.11.20", features = ["native-tls-vendored", "multipart", "blocking"] }
hyper = "0.14"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
serde.workspace = true
serde_json.workspace = true
serde-aux = "4.2.0"
thiserror = "1.0"
tokio = { workspace = true, features = ["sync"]}
parking_lot.workspace = true
lazy_static = "1.4.0"
bytes = { workspace = true, features = ["serde"] }
tokio-retry = "0.3"
anyhow.workspace = true
uuid.workspace = true
chrono = { workspace = true,  default-features = false, features = ["clock", "serde"] }
collab = { version = "0.1.0" }
collab-plugins = { version = "0.1.0"}
collab-document = { version = "0.1.0" }
collab-entity = { version = "0.1.0" }
hex = "0.4.3"
postgrest = "1.0"
lib-infra = { path = "../../../shared-lib/lib-infra" }
flowy-user-deps = { workspace = true }
flowy-folder-deps  = { workspace = true }
flowy-database-deps = { workspace = true }
flowy-document-deps = { workspace = true }
flowy-error = { workspace = true, features = ["impl_from_postgres", "impl_from_serde", "impl_from_reqwest", "impl_from_url", "impl_from_appflowy_cloud"] }
flowy-server-config = { workspace = true }
flowy-encrypt = { workspace = true }
flowy-storage = { workspace = true }
mime_guess = "2.0"
url = "2.4"
tokio-util = "0.7"
tokio-stream = { workspace = true, features = ["sync"] }
client-api = { version = "0.1.0", features = ["collab-sync", "test_util"] }
lib-dispatch = { workspace = true }

[dev-dependencies]
uuid.workspace = true
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
dotenv = "0.15.0"
yrs = "0.16.5"
assert-json-diff = "2.0.2"
serde_json.workspace = true
client-api = { version = "0.1.0" }
