[package]
name = "event-integration-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-core = { workspace = true }
flowy-user = { workspace = true }
flowy-user-pub = { workspace = true }
flowy-folder = { path = "../flowy-folder", features = ["test_helper"] }
flowy-folder-pub = { workspace = true }
flowy-database2 = { path = "../flowy-database2" }
flowy-database-pub = { workspace = true }
flowy-document = { path = "../flowy-document" }
flowy-document-pub = { workspace = true }
flowy-encrypt = { workspace = true }
flowy-chat = { workspace = true }
lib-dispatch = { workspace = true }
lib-infra = { workspace = true }
flowy-server = { path = "../flowy-server" }
flowy-server-pub = { workspace = true }
flowy-notification = { workspace = true }
anyhow.workspace = true
flowy-storage = { workspace = true }
flowy-search = { workspace = true }

serde.workspace = true
serde_json.workspace = true
protobuf.workspace = true
tokio = { workspace = true, features = ["full"] }
futures-util = "0.3.26"
thread-id = "3.3.0"
bytes.workspace = true
nanoid = "0.4.0"
tracing.workspace = true
parking_lot.workspace = true
uuid.workspace = true
collab = { workspace = true }
collab-document = { workspace = true }
collab-folder = { workspace = true }
collab-database = { workspace = true }
collab-plugins = { workspace = true }
collab-entity = { workspace = true }
rand = { version = "0.8.5", features = [] }
strum = "0.25.0"

[dev-dependencies]
dotenv = "0.15.0"
tempdir = "0.3.7"
uuid.workspace = true
assert-json-diff = "2.0.2"
tokio-postgres = { version = "0.7.8" }
chrono = "0.4.31"
zip = "0.6.6"
walkdir = "2.5.0"
futures = "0.3.30"

[features]
default = ["supabase_cloud_test"]
dart = ["flowy-core/dart"]
supabase_cloud_test = []
single_thread = []