[package]
name = "lib-infra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { workspace = true,  default-features = false, features = ["clock"] }
bytes = { version = "1.5" }
pin-project = "1.1.3"
futures-core = { version = "0.3" }
tokio = { workspace = true, features = ["time", "rt"] }
async-trait.workspace = true
md5 = "0.7.0"
anyhow.workspace = true
walkdir = "2.4.0"
tempfile = "3.8.1"
validator = "0.16.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
zip = "0.6.6"
