[package]
name = "flowy-ai-pub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-infra = { workspace = true }
flowy-error = { workspace = true }
client-api = { workspace = true }
futures.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
flowy-sqlite = { workspace = true }
chrono.workspace = true