[package]
name = "flowy-sdk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-dispatch = { path = "../lib-dispatch" }
lib-log = { path = "../lib-log" }
flowy-user = { path = "../flowy-user" }
flowy-net = { path = "../flowy-net" }
flowy-folder = { path = "../flowy-folder", default-features = false }
flowy-grid = { path = "../flowy-grid", default-features = false }
grid-rev-model = { path = "../../../shared-lib/grid-rev-model" }
flowy-database = { path = "../flowy-database" }
flowy-document = { path = "../flowy-document", default-features = false }
flowy-revision = { path = "../flowy-revision" }

tracing = { version = "0.1" }
log = "0.4.14"
futures-core = { version = "0.3", default-features = false }
color-eyre = { version = "0.5", default-features = false }
bytes = "1.0"
tokio = { version = "1", features = ["rt"] }
parking_lot = "0.12.1"

flowy-sync = { path = "../../../shared-lib/flowy-sync" }
lib-ws = { path = "../../../shared-lib/lib-ws" }
lib-infra = { path = "../../../shared-lib/lib-infra" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.3" }
protobuf = { version = "2.24.1" }
claim = "0.5.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.15"

[features]
http_sync = ["flowy-folder/cloud_sync", "flowy-document/cloud_sync"]
native_sync = ["flowy-folder/cloud_sync", "flowy-document/cloud_sync"]
use_bunyan = ["lib-log/use_bunyan"]
dart = [
    "flowy-user/dart",
    "flowy-net/dart",
    "flowy-folder/dart",
    "flowy-sync/dart",
    "flowy-grid/dart",
    "flowy-document/dart",
]
openssl_vendored = ["flowy-database/openssl_vendored"]
