[package]
name = "flowy-error"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-derive = { path = "../../../shared-lib/flowy-derive" }
protobuf.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror = "1.0"
validator = "0.16.0"
tokio = { workspace = true, features = ["sync"]}

fancy-regex = { version = "0.11.0" }
lib-dispatch = { workspace = true, optional = true }
serde_json.workspace = true
serde_repr.workspace = true
serde.workspace = true
reqwest = { version = "0.11.14", optional = true, features = [
    "native-tls-vendored",
] }
flowy-sqlite = { workspace = true, optional = true }
r2d2 = { version = "0.8", optional = true }
url = { version = "2.2", optional = true }
collab-database = { version = "0.1.0", optional = true }
collab-document = { version = "0.1.0", optional = true }
collab-persistence = { version = "0.1.0", optional = true }
tokio-postgres = { version = "0.7.8", optional = true }
client-api = { version = "0.1.0", optional = true }

[features]
default = ["impl_from_appflowy_cloud", "impl_from_collab", "impl_from_reqwest", "impl_from_serde"]
impl_from_dispatch_error = ["lib-dispatch"]
impl_from_serde = []
impl_from_reqwest = ["reqwest"]
impl_from_sqlite = ["flowy-sqlite", "r2d2"]
impl_from_collab = ["collab-database", "collab-document", "impl_from_reqwest", "collab-persistence"]
impl_from_postgres = ["tokio-postgres"]
impl_from_url = ["url"]
impl_from_appflowy_cloud = ["client-api"]
dart = ["flowy-codegen/dart"]
ts = ["flowy-codegen/ts"]

[build-dependencies]
flowy-codegen = { path = "../../../shared-lib/flowy-codegen", features = [
    "proto_gen",
] }
