[package]
name = "flowy-http-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0"
lib-infra = { path = "../lib-infra" }
flowy-derive = { path = "../flowy-derive" }
protobuf = {version = "2.18.0"}
md5 = "0.7.0"
serde = {versino = "1.0"}
serde_json = { version = "1.0" }
serde_repr = "0.1"

[build-dependencies]
flowy-codegen = { path = "../flowy-codegen", features = ["proto_gen"]}


