[package]
name = "flowy-date"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lib-dispatch = { path = "../lib-dispatch" }
flowy-error = { path = "../flowy-error" }
flowy-derive.workspace = true
protobuf.workspace = true
bytes.workspace = true
strum_macros = "0.21"
tracing.workspace = true
date_time_parser = { version = "0.2.0" }
chrono.workspace = true
fancy-regex = { version = "0.11.0" }

[build-dependencies]
flowy-codegen.workspace = true

[features]
dart = ["flowy-codegen/dart"]
tauri_ts = ["flowy-codegen/ts"]
