[package]
name = "lib-log"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tracing-log = { version = "0.2"}
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter", "ansi", "json"] }
tracing-bunyan-formatter = "0.3.9"
tracing-appender = "0.2.2"
tracing-core = "0.1"
tracing = { version = "0.1", features = ["log"] }
log = "0.4.17"
serde_json = "1.0"
serde = "1.0"
chrono = "0.4"
lazy_static = "1.4.0"

[features]
use_bunyan = []
