[package]
name = "flowy-sqlite"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel.workspace = true
diesel_derives = { version = "2.1.0", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

r2d2 = "0.8.10"
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] }
scheduled-thread-pool = "0.2.6"
openssl = { version = "0.10.62", optional = true, features = ["vendored"] }
openssl-sys = { version = "0.9.98", optional = true, features = ["vendored"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.5.0"

[features]
openssl_vendored = ["openssl", "openssl-sys"]
