name: appflowy_ui_example
description: "Example app showcasing AppFlowy UI components and widgets"
publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ">=3.27.4"
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  appflowy_ui:
    path: ../
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/vector.svg
    - assets/images/arrow_right.svg
