[package]
name = "flowy-folder-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-infra = { path = "../../../shared-lib/lib-infra" }
flowy-error = { path = "../flowy-error" }
collab-folder = { version = "0.1.0" }
uuid = { version = "1.3.3", features = ["v4"] }
anyhow = "1.0.71"