[package]
name = "flowy-document2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { version = "0.1.0" }
collab-document = { version = "0.1.0" }
appflowy-integrate = {version = "0.1.0" }

flowy-derive = { path = "../../../shared-lib/flowy-derive" }
flowy-notification = { path = "../flowy-notification" }
flowy-error = { path = "../flowy-error", features = ["adaptor_serde", "adaptor_database", "adaptor_dispatch", "collab"] }
lib-dispatch = { path = "../lib-dispatch" }

protobuf = {version = "2.28.0"}
bytes = { version = "1.4" }
nanoid = "0.4.0"
parking_lot = "0.12.1"
strum = "0.21"
strum_macros = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0"}
tracing = { version = "0.1", features = ["log"] }
tokio = { version = "1.26", features = ["full"] }
anyhow = "1.0"
indexmap = {version = "1.9.2", features = ["serde"]}

[dev-dependencies]
tempfile = "3.4.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }

[build-dependencies]
flowy-codegen = { path = "../../../shared-lib/flowy-codegen"}

[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
ts = ["flowy-codegen/ts", "flowy-notification/ts"]

