[package]
name = "flowy-folder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { workspace = true }
collab-folder = { workspace = true }
collab-document = { workspace = true }
collab-entity = { workspace = true }
collab-plugins = { workspace = true }
collab-integrate = { workspace = true }
flowy-folder-pub = { workspace = true }
flowy-search-pub = { workspace = true }
flowy-notification = { workspace = true }
arc-swap.workspace = true
unicode-segmentation = "1.10"
tracing.workspace = true
flowy-derive.workspace = true
flowy-sqlite = { workspace = true }
flowy-error = { path = "../flowy-error", features = [
  "impl_from_dispatch_error",
  "impl_from_collab_folder",
  "impl_from_sqlite",
  "impl_from_collab_persistence",
] }
lib-dispatch = { workspace = true }
bytes.workspace = true
lib-infra = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
nanoid = "0.4.0"
lazy_static = "1.4.0"
chrono = { workspace = true, default-features = false, features = ["clock"] }
strum_macros = "0.21"
protobuf.workspace = true
uuid.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
validator.workspace = true
async-trait.workspace = true
client-api = { workspace = true }
regex = "1.9.5"
futures = "0.3.31"
dashmap.workspace = true
diesel.workspace = true
diesel_derives = { version = "2.1.0", features = ["sqlite", "r2d2"] }
num="0.4.3"
num-traits = "0.2.19"
num-derive = "0.4.2"

[build-dependencies]
flowy-codegen.workspace = true

[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
test_helper = []
