[package]
name = "appflowy-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2.89" }
lazy_static = "1.4.0"
lib-dispatch = { workspace = true, features = ["wasm_build"] }
parking_lot.workspace = true
tracing.workspace = true
tracing-core = { version = "0.1.32" }
tracing-wasm = "0.2.1"
flowy-notification = { workspace = true, features = ["ts"] }

[workspace.dependencies]
lib-dispatch = { path = "../../rust-lib/lib-dispatch" }
parking_lot = { version = "0.12.1" }
tracing = { version = "0.1.22" }
flowy-notification = { path = "../../rust-lib/flowy-notification" }
