name: appflowy_editor
description: A highly customizable rich-text editor for Flutter
version: 0.0.9
homepage: https://github.com/AppFlowy-IO/AppFlowy

platforms:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  rich_clipboard: ^1.0.0
  html: ^0.15.0
  flutter_svg: ^2.0.2
  provider: ^6.0.3
  url_launcher: ^6.1.5
  logging: ^1.0.2
  intl_utils: ^2.7.0
  intl:
  flutter_localizations:
    sdk: flutter
  markdown: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  network_image_mock: ^2.1.1
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/toolbar/
    - assets/images/selection_menu/
    - assets/images/image_toolbar/
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  class_name: AppFlowyEditorLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/src/l10n
  use_deferred_loading: false
  localizely:
    project_id: b7199c7d-eca0-4025-894d-230cdcafa9aa
