[package]
name = "flowy-notification"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = { version = "1.4.0" }
protobuf.workspace = true
tracing.workspace = true
bytes.workspace = true
serde = { workspace = true, features = ["derive"] }
dashmap.workspace = true
tokio-util = "0.7"
tokio = { workspace = true, features = ["time"] }

flowy-derive.workspace = true
lib-dispatch = { workspace = true }

[build-dependencies]
flowy-codegen.workspace = true

[features]
dart = ["flowy-codegen/dart"]
tauri_ts = ["flowy-codegen/ts"]
web_ts = ["flowy-codegen/ts"]
