[package]
name = "lib-infra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
bytes = { version = "1.5" }
pin-project = "1.1.3"
futures-core = { version = "0.3" }
tokio = { version = "1.26", features = ["time", "rt"] }
rand = "0.8.5"
async-trait = "0.1.64"
md5 = "0.7.0"
anyhow = "1.0"
