[package]
name = "lib-infra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4.14"
chrono = "0.4.19"
bytes = { version = "1.0" }
pin-project = "1.0"
futures-core = { version = "0.3", default-features = false }
tokio = { version = "1.0", features = ["time", "rt"] }
rand = "0.8.3"

cmd_lib = { version = "1", optional = true }
protoc-rust = { version = "2", optional = true }
walkdir = { version = "2", optional = true }

[features]
pb_gen = ["cmd_lib", "protoc-rust", "walkdir"]
dart = []