[package]
name = "flowy-user"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-derive = { path = "../flowy-derive" }
flowy-database = { path = "../flowy-database", optional = true }
flowy-error = { path = "../flowy-error", features = ["db", "http_server", "dispatch"] }
user-model = { path = "../../../shared-lib/user-model" }
lib-infra = { path = "../../../shared-lib/lib-infra" }
flowy-notification = { path = "../flowy-notification" }
lib-dispatch = { path = "../lib-dispatch" }

tracing = { version = "0.1", features = ["log"] }
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0"}
log = "0.4.14"
protobuf = {version = "2.18.0"}
lazy_static = "1.4.0"
diesel = {version = "1.4.8", features = ["sqlite"]}
diesel_derives = {version = "1.4.1", features = ["sqlite"]}
once_cell = "1.7.2"
parking_lot = "0.12.1"
strum = "0.21"
strum_macros = "0.21"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
flowy-test = { path = "../flowy-test" }

[features]
rev-sqlite = ["flowy-database"]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
ts = ["flowy-codegen/ts", "flowy-notification/ts"]

[build-dependencies]
flowy-codegen = { path = "../flowy-codegen"}
