[package]
name = "flowy-user"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-derive.workspace = true
flowy-sqlite = { workspace = true }
flowy-encrypt = { workspace = true }
flowy-error = { workspace = true, features = ["impl_from_dispatch_error", "impl_from_sqlite", "impl_from_collab_folder", "impl_from_collab_persistence"] }
flowy-folder-pub = { workspace = true }
lib-infra = { workspace = true }
flowy-notification = { workspace = true }
flowy-server-pub = { workspace = true }
lib-dispatch = { workspace = true }
collab-integrate = { workspace = true }
collab = { version = "0.1.0" }
collab-folder = { version = "0.1.0" }
collab-document = { version = "0.1.0" }
collab-database = { version = "0.1.0" }
collab-user = { version = "0.1.0" }
collab-entity = { version = "0.1.0" }
collab-plugins = { version = "0.1.0" }
flowy-user-pub = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
protobuf.workspace = true
lazy_static = "1.4.0"
diesel.workspace = true
diesel_derives = { version = "2.1.0", features = ["sqlite", "r2d2"] }
once_cell = "1.17.1"
parking_lot.workspace = true
strum = "0.25"
strum_macros = "0.25.2"
tokio = { workspace = true, features = ["rt"] }
validator = "0.16.0"
unicode-segmentation = "1.10"
fancy-regex = "0.11.0"
uuid.workspace = true
chrono = { workspace = true, default-features = false, features = ["clock"] }
base64 = "^0.21"
tokio-stream = "0.1.14"
semver = "1.0.22"

[dev-dependencies]
nanoid = "0.4.0"
fake = "2.0.0"
rand = "0.8.4"
quickcheck = "1.0.3"
rand_core = "0.6.2"
quickcheck_macros = "1.0"

[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
tauri_ts = ["flowy-codegen/ts", "flowy-notification/tauri_ts"]

[build-dependencies]
flowy-codegen.workspace = true
