[package]
name = "flowy-user"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-derive = { path = "../../../shared-lib/flowy-derive" }
flowy-database = { path = "../flowy-database" }
flowy-error = { path = "../flowy-error", features = ["db", "http_server"] }

lib-infra = { path = "../../../shared-lib/lib-infra" }
dart-notify = { path = "../dart-notify" }
lib-dispatch = { path = "../lib-dispatch" }

tracing = { version = "0.1", features = ["log"] }
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0"}
log = "0.4.14"
protobuf = {version = "2.18.0"}
lazy_static = "1.4.0"
diesel = {version = "1.4.8", features = ["sqlite"]}
diesel_derives = {version = "1.4.1", features = ["sqlite"]}
once_cell = "1.7.2"
parking_lot = "0.12.1"
strum = "0.21"
strum_macros = "0.21"
tokio = { version = "1", features = ["rt"] }
unicode-segmentation = "1.8"
validator = "0.15"
fancy-regex = "0.10.0"

[dev-dependencies]
flowy-test = { path = "../flowy-test" }
nanoid = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "0.9.1"
fake = "2.4.3"
claim = "0.4.0"
futures = "0.3.15"
serial_test = "0.5.1"
rand_core = "0.6.3"
rand = "0.8.5"

[features]
dart = ["lib-infra/dart"]

[build-dependencies]
lib-infra = { path = "../../../shared-lib/lib-infra", features = ["protobuf_file_gen"] }