[package]
name = "flowy-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flowy-derive.workspace = true
flowy-notification = { workspace = true }
flowy-error = { path = "../flowy-error", features = [
  "impl_from_dispatch_error",
  "impl_from_collab_folder",
  "impl_from_sqlite",
  "impl_from_appflowy_cloud",
] }
lib-dispatch = { workspace = true }
tracing.workspace = true
uuid.workspace = true
strum_macros = "0.21"
protobuf.workspace = true
bytes.workspace = true
arc-swap.workspace = true
validator = { workspace = true, features = ["derive"] }
lib-infra = { workspace = true, features = ["isolate_flutter"] }
flowy-ai-pub.workspace = true
dashmap.workspace = true
flowy-sqlite = { workspace = true }
tokio.workspace = true
futures.workspace = true
allo-isolate = { version = "^0.1", features = ["catch-unwind"] }
log = "0.4.21"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = "1.0.86"
tokio-stream = "0.1.15"
tokio-util = { workspace = true, features = ["full"] }
af-local-ai = { workspace = true }
af-plugin = { workspace = true }
reqwest = { version = "0.11.27", features = ["json"] }
sha2 = "0.10.7"
base64 = "0.21.5"
futures-util = "0.3.30"
pin-project = "1.1.5"
flowy-storage-pub = { workspace = true }


[target.'cfg(any(target_os = "macos", target_os = "linux", target_os = "windows"))'.dependencies]
notify = "6.1.1"
ollama-rs = "0.3.0"
af-mcp = { version = "0.1.0" }
twox-hash = { version = "2.1.0", features = ["xxhash64"] }
text-splitter = { version = "0.25.1" }
flowy-sqlite-vec.workspace = true


[dev-dependencies]
uuid.workspace = true

[build-dependencies]
flowy-codegen.workspace = true


[features]
dart = ["flowy-codegen/dart", "flowy-notification/dart"]
local_ai = []
