# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"

jobs:
  flutter-analyze:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable-2022-01-20"

      - name: Rust Deps
        working-directory: frontend
        run: |
          cargo install cargo-make
          cargo make flowy_dev

      - name: Flutter Deps
        run: flutter packages pub get
        working-directory: frontend/app_flowy

      - name: Build FlowySDK
        working-directory: frontend
        run: |
          cargo make --profile development-linux-x86_64 flowy-sdk-dev

      - name: Code Generation
        working-directory: frontend/app_flowy
        run: |
          flutter packages pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations -s en.json
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyzer
        working-directory: frontend/app_flowy
        run: flutter analyze
