name: Unit test(Flutter)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Deps Rust
        working-directory: frontend
        run: |
          cargo install --force cargo-make
          cargo install --force duckscript_cli
          cargo make flowy_dev
          echo PATH="$PATH":"$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Deps Flutter
        run: flutter packages pub get
        working-directory: frontend/app_flowy
      - name: Code Generation
        working-directory: frontend/app_flowy
        run: |
          flutter packages pub run easy_localization:generate -S ./assets/translations -f keys -O lib/generated -o locale_keys.g.dart
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Build FlowySDK
        working-directory: frontend
        run: |
          flutter config --enable-linux-desktop
          cargo make --profile development-linux-x86 flowy-sdk-dev
      - name: Run bloc tests
        working-directory: frontend/app_flowy
        run: |
          flutter test

