# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  flutter-analyze:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
          channel: "stable"
      - name: Deps Flutter
        run: flutter packages pub get
        working-directory: frontend/app_flowy
      - name: Code Generation
        working-directory: frontend/app_flowy
        run: |
          flutter packages pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations -s en.json
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run Flutter Analyzer
        working-directory: frontend/app_flowy
        run: flutter analyze

