name: Deploy

on:
  push:
    branches:
      - build/test
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'test'
env:
  NODE_VERSION: "18.16.0"
  PNPM_VERSION: "8.5.0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Node_modules cache
        uses: actions/cache@v2
        with:
          path: frontend/appflowy_web_app/node_modules
          key: node-modules-${{ runner.os }}
      - name: install frontend dependencies
        working-directory: frontend/appflowy_web_app
        run: |
          pnpm install
      - name: generate env file (Test)
        if: github.event.inputs.environment == 'test' || github.ref == 'refs/heads/build/test'
        working-directory: frontend/appflowy_web_app
        run: |
          cp test.env .env
      - name: generate env file (Prod)
        if: github.event.inputs.environment == 'prod'
        working-directory: frontend/appflowy_web_app
        run: |
          cp beta.env .env
      - name: test and lint
        working-directory: frontend/appflowy_web_app
        run: |
          pnpm run lint
      - name: build
        working-directory: frontend/appflowy_web_app
        run: |
          pnpm run build
      - name: Archive build output
        working-directory: frontend/appflowy_web_app
        run: |
          tar -czf build-output.tar.gz dist server.cjs start.sh Dockerfile nginx.conf .env

      - name: Deploy to EC2 (Test)
        if: github.event.inputs.environment == 'test' || github.ref == 'refs/heads/build/test'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.WEB_TEST_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: build-output.tar.gz deploy.sh
          TARGET: /home/${{ secrets.WEB_TEST_REMOTE_USER }}/appflowy-web-app
          REMOTE_HOST: ${{ secrets.WEB_TEST_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.WEB_TEST_REMOTE_USER }}
          SCRIPT_AFTER: |
            cd appflowy-web-app
            chmod +x deploy.sh
            sh deploy.sh
      - name: Deploy to EC2 (Prod)
        if: github.event.inputs.environment == 'prod'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.WEB_PROD_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          TARGET: /home/${{ secrets.WEB_PROD_REMOTE_USER }}/appflowy-web-app
          SOURCE: build-output.tar.gz deploy.sh
          REMOTE_HOST: ${{ secrets.WEB_PROD_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.WEB_PROD_REMOTE_USER }}
          SCRIPT_AFTER: |
            cd appflowy-web-app
            chmod +x deploy.sh
            sh deploy.sh