name: Tauri-CI
on:
  pull_request:
    paths:
      - "frontend/rust-lib/**"
      - "frontend/appflowy_tauri/**"

env:
  NODE_VERSION: "18.16.0"
  PNPM_VERSION: "8.5.0"
  RUST_TOOLCHAIN: "1.65"

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
#        platform: [macos-latest, ubuntu-latest, windows-latest]
         platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Rust toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'ubuntu-latest-tauri'
          workspaces: |
            frontend/rust-lib 
            frontend/appflowy_tauri/src-tauri

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        working-directory: frontend
        run: |
          cargo install --force cargo-make
          cargo install --force duckscript_cli
          vcpkg integrate install
          cargo make appflowy-tauri-deps-tools
          npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        working-directory: frontend
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          cargo install --force cargo-make
          cargo make appflowy-tauri-deps-tools
          npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: install dependencies (macOS only)
        if: matrix.platform == 'macos-latest'
        working-directory: frontend
        run: |
          cargo install --force cargo-make
          cargo make appflowy-tauri-deps-tools
          npm install -g pnpm@${{ env.PNPM_VERSION }}


      - name: build
        working-directory: frontend/appflowy_tauri
        run: |
          mkdir dist
          pnpm install
          cargo make --cwd .. tauri_build
          pnpm test:errors

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
